name: prettier

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm test

    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        prettier_options: --write **/*.{js,json}
        same_commit: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
